### ISSUE TITLE
Provide source please

### ISSUE THREAD

**Issue by D3vl0per** [alanferreiravalorant/valorantbot#1]
Hi!
I am the owner of the original valorant-watcher repo.
I saw you don't fork my project, just copied and renamed it.
Please remove my support address from the readme and provide the source!

Thanks!
D3v

**Comment by D3vl0per** [comment]
I need to report to admin if you left my address in readme and provide the source please!

**Comment by D3vl0per** [comment]
@alanferreiravalorant

**Comment by D3vl0per** [comment]
@alanferreiravalorant I reported you abuse of my personal information.
Why are you just forking the project?

**Comment by D3vl0per** [comment]
> @D3vl0per Sorry, i'm using your source for personal use

Why are you stole the looking, code and others? I saw your every commit! Do you think I'm stupid Just personal use? Download it, and fine. But you create an account with alanferreira**valorant** name after I published my code and also copied and renamed it.

**Comment by alanferreiravalorant** [comment]
@D3vl0per Im type message in chat community

**Comment by D3vl0per** [comment]
I saw your last commit!
Thanks!

**Comment by D3vl0per** [comment]
Everything already fine!
We solved these things!
